sorting created items by creation date (bugs to fix yet!)
the following error must be resolved :

FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/finance-tracker-fac6e/firestore/indexes?create_composite=Clpwcm9qZWN0cy9maW5hbmNlLXRyYWNrZXItZmFjNmUvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3RyYW5zYWN0aW9ucy9pbmRleGVzL18QARoHCgN1aWQQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC